import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import { i18n, Locale } from '@/i18n.config';
import RootProvider from './components/RootProvider';
import { getDictionary } from '@/lib/dictionary';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const source_sans = Source_Sans_3({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Alex Pervitin',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const { tr } = await getDictionary(params.lang);

  return (
    <html lang={params.lang}>
      <body className={source_sans.className}>
        <RootProvider tr={tr}>{children}</RootProvider>
        <ToastContainer newestOnTop />
      </body>
    </html>
  );
}
